//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PROVEEDOR
    {
        public int idProductoProveedor { get; set; }
        public int idProducto { get; set; }
        public int idProveedor { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> idUnidadDeMedida { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual UNIDAD_DE_MEDIDA UNIDAD_DE_MEDIDA { get; set; }
    }
}
